name: hue_rotation_example
description: Demonstrates how to use the hue_rotation plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  hue_rotation:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
