name: hue_rotation_example
description: Demonstrates how to use the hue_rotation package.

publish_to: 'none'

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  hue_rotation:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
