name: hue_rotation
description: Change the color of any widget that has a color, like SwiftUI's Hue Rotation.
version: 1.0.0
homepage: https://github.com/nohli/hue_rotation

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.25.0-0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  plugin:
    platforms:
      android:
        package: com.achimsapps.hue_rotation
        pluginClass: HueRotationPlugin
      ios:
        pluginClass: HueRotationPlugin
      macos:
        pluginClass: HueRotationPlugin
      windows:
        pluginClass: HueRotationPlugin
      linux:
        pluginClass: HueRotationPlugin
      web:
        fileName: hue_rotation_web.dart
        pluginClass: HueRotationWeb
