name: hue_rotation
description: Change the color of any widget that has a color. Like SwiftUI's Hue Rotation.

repository: https://github.com/nohli/hue_rotation
issue_tracker: https://github.com/nohli/hue_rotation/issues

topics:
  - animation
  - hue
  - color
  - ui

version: 1.3.9

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ">=2.0.0 <4.0.0"
  flutter_test:
    sdk: flutter
